[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
calloop = "0.14.3"
calloop-wayland-source = "0.4.1"
clap = { version = "4.5.48", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.28"
nix = "0.30.1"
tempfile = "3.23.0"
wayland-client = "0.31.11"
wayland-protocols-misc = { version = "0.3.9", features = ["client"] }
wayland-protocols-wlr = { version = "0.3.9", features = ["client"] }
xkbcommon = "0.9.0"
